services:
  - type: web
    name: student-companion-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: INTERNAL_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://student-companion-frontend.onrender.com

  - type: web
    name: student-companion-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://student-companion-api-zrcv.onrender.com
      - key: NEXTAUTH_URL
        value: https://student-companion-frontend.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
      - key: INTERNAL_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_FEATURE_TASK_SEARCH
        value: false
